Feature/prd 24 backend authentication service
amt-charles-biney/gpu-configurator pull request #13
Opened 2023-12-14 10:20 UTC by Zena4L

This is the whole authentication flow.

2023-12-19 11:16 UTC, Gabriel-Rockson requested changes

2023-12-19 11:16 UTC, Gabriel-Rockson commented on .sample.env
rename this to `.example.env` it's a convention

2023-12-19 11:16 UTC, Gabriel-Rockson commented on pom.xml
> +			<groupId>me.paulschwarz</groupId>
Spring has a way of dealing with environment variables without need for a third party package, get rid of the dependency and use the built-in functionality

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/config/JwtAuthenticationFilter.java
> +        if (authenticationHeader == null || !authenticationHeader.startsWith("Bearer")) {
You should rather be checking for the existence of 'Bearer ' as a token of `BearerE92dafd89adfa223fadf232fadf...` will still match your conditional check. The authenticationHeader.subString(7) will then extract the wrong token in this case.

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/config/JwtAuthenticationFilter.java
> +    public final JwtServiceImpl jwtServiceImpl;
You should be programming to interfaces and not implementations, use the JwtService interface instead of the hard implementation for the type

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/controller/AuthController.java
> +    private final UserService userServiceImpl;
The variable name can just be `userService`, `userServiceImpl` makes it seem we are using the actual implementation in here

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/dto/SignUpDto.java
> +    @Size(min = 4, message = "Password must be a minimum of 4 characters")
It's best to have a password length of 8 and above, 4 is bad

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/dto/SignUpDto.java
The formatting of this file is not consistent with other files.

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/dto/UserDto.java
> +    @Size(min = 6, message = "Password must have at least 6 characters")
Have a consistent minimum password length across the application. You could define a constant in a constants file and use the min value everywhere

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/dto/VerifyOtpDTO.java
> +    @Email(message = "Invalid email format")
Due to the repetitive nature of some of these errors in your application, I'd suggest you have constants defined to hold these error messages and use a similar error message in all DTOs that needs such message

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/exception/CustomExceptionHandler.java
> +    public ProblemDetail handleBadCredentialException(Exception e) {
Any reason why these methods are nested?

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/exception/CustomExceptionHandler.java
I am guessing the formatting of the file is not right, please format the file properly. It'll be a good idea for all developers on the project to setup a similar formatting and linting strategy in your IDEs or within the project configuration.

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/service/jwt/JwtServiceImpl.java
> +     *
Too many redundant comments

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/main/resources/application.properties
> +spring.mail.host=smtp.gmail.com
I'd rather not have the email host and port exposed in here, it's best to have that in an env as well

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/test/java/com/amalitech/gpuconfigurator/GpuConfiguratorApplicationTests.java
> +	@Test
What's the point of this test??? I don't see relevance to application

2023-12-19 11:16 UTC, Gabriel-Rockson commented on src/test/java/com/amalitech/gpuconfigurator/service/EmailServiceTest.java
> +    public void sendOtpMessage_shouldProcessTemplateAndSendMessage() throws MessagingException {
Remove commented out code from codebase

2023-12-19 11:20 UTC, Gabriel-Rockson requested changes

2023-12-19 11:20 UTC, Gabriel-Rockson commented on src/test/java/com/amalitech/gpuconfigurator/repository/UserRepositoryTest.java
> +package com.amalitech.gpuconfigurator.repository;
Since your repository is just implementing JPARepository, you don't necessarily need a test file for your repository. Remove file

2023-12-19 12:38 UTC, Zena4L commented on src/main/java/com/amalitech/gpuconfigurator/config/JwtAuthenticationFilter.java
> +        if (authenticationHeader == null || !authenticationHeader.startsWith("Bearer")) {
jwtToken = authenticationHeader.substring(7); to fix that.

2023-12-19 14:03 UTC, Zena4L commented on pom.xml
> +			<groupId>me.paulschwarz</groupId>
Ok, we have a little challenge with this. we will fix it.

2023-12-19 16:10 UTC, Gabriel-Rockson commented
Errmm, just so you know marking Conversations as resolved is done by the person who is requesting changes.

2023-12-19 16:12 UTC, Gabriel-Rockson requested changes

2023-12-19 16:12 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/config/JwtAuthenticationFilter.java
> +        if (authenticationHeader == null || !authenticationHeader.startsWith("Bearer")) {
What I mean is, you will want to check if the authentication header begins with "Bearer " and not "Bearer", notice the extra space after the Bearer

2023-12-20 15:41 UTC, Gabriel-Rockson requested changes

2023-12-20 15:41 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/util/ValidationErrorMessages.java
Use a normal class

2023-12-20 16:12 UTC, elitekaycy commented on src/main/java/com/amalitech/gpuconfigurator/util/ValidationErrorMessages.java
done

2023-12-20 16:18 UTC, Gabriel-Rockson commented on src/main/java/com/amalitech/gpuconfigurator/util/ValidationErrorMessages.java
It'll be nice to later move this file into a package with name `constants` instead of utils

2023-12-20 16:18 UTC, Gabriel-Rockson approved these changes

2023-12-20 16:24 UTC, merged